languageCode = "it"
languageName = "Italiano"
weight = 2
title = "The Crib"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.svg"
  description = "Articoli a caso sull'informatica"

[params.author]
  name = "ShadowRocket227"
  image = "https://avatars.githubusercontent.com/u/137918363?v=4"
  headline = "Informatico indipendente"
  bio = "Nato e cresciuto in /dev/random"
  
  links = [
    { github = "https://github.com/ShadowRocket227" },
  ]
