languageCode = "it"
languageName = "Italiano"
weight = 2
title = "The Crib"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  description = "Articoli a caso sull'informatica"

[params.author]
  name = "Ettore Ronchini"
  email = "ettoreronchini10@gmail.com"
  image = "https://avatars.githubusercontent.com/u/137918363?v=4"
  headline = "Informatico indipendente"
  bio = "Hi, my name is...ChickaChickaChika Slim Shady !"
  
  links = [
    { github = "https://github.com/ShadowRocket227" },
    { email = "mailto:ettoreronchini10@gmail.com" },
  ]
